# Generated by Django 5.2 on 2025-05-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='kathmandu', max_length=200),
            preserve_default=False,
        ),
    ]
