# Generated by Django 5.2 on 2025-05-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='od_0a264640', primary_key=True, serialize=False, unique=True),
        ),
    ]
