# Generated by Django 5.2 on 2025-05-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='od_3758fce3', primary_key=True, serialize=False, unique=True),
        ),
    ]
