# Generated by Django 5.2 on 2025-05-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='od_3a7eb494', primary_key=True, serialize=False, unique=True),
        ),
    ]
