# Generated by Django 5.2 on 2025-05-16 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_alter_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='other_colors',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='other_sizes',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='od_9869ca0f', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(max_length=210, unique=True),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('in_stock', models.BooleanField(default=False)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.productcolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='commerce.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.productsize')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'size', 'color'), name='unique_product_variant')],
            },
        ),
    ]
