# Generated by Django 5.2 on 2025-05-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_product_color_product_size_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='od_9b44eea9', primary_key=True, serialize=False, unique=True),
        ),
    ]
