# Generated by Django 5.2 on 2025-05-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='od_fe5b0065', primary_key=True, serialize=False, unique=True),
        ),
    ]
