# Generated by Django 5.2 on 2025-05-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='od_a1555e2f', primary_key=True, serialize=False, unique=True),
        ),
    ]
