# Generated by Django 5.2 on 2025-05-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_cart_id_alter_cart_cart_id_alter_order_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='od_8aafcb18', primary_key=True, serialize=False, unique=True),
        ),
    ]
