# Generated by Django 5.2 on 2025-05-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0016_alter_cart_cart_id_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='od_847100f0', primary_key=True, serialize=False, unique=True),
        ),
    ]
