# Generated by Django 5.2 on 2025-05-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0017_alter_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='od_e5f6a8bf', primary_key=True, serialize=False, unique=True),
        ),
    ]
