# Generated by Django 5.2 on 2025-05-19 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0018_remove_cartitem_product_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commerce.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='od_d42e8e69', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='stars',
            field=models.CharField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], max_length=10),
        ),
    ]
