# Generated by Django 5.2 on 2025-05-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0019_cartitem_product_alter_order_order_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserComments',
            new_name='UserComment',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='od_299f9bbe', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='stars',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=10),
        ),
    ]
