# Generated by Django 5.2 on 2025-05-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0021_remove_product_comment_remove_product_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='od_f177bdb5', primary_key=True, serialize=False, unique=True),
        ),
    ]
