# Generated by Django 5.2 on 2025-05-28 04:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_order_id_alter_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='completed_by',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='od_9e99d371', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Refund', 'Refund'), ('Cancelled', 'Cancel'), ('Failed', 'Failed'), ('Processing', 'Processing')], default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('a1a66fb8-72e0-4b49-b750-1336cc7c7ae5')),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_log', to='order.order'),
        ),
    ]
