# Generated by Django 5.2 on 2025-05-28 04:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderhistory_completed_by_alter_order_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='od_899477b2', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('7d34422e-5660-4edb-97de-016cd48b6c8b')),
        ),
    ]
