# Generated by Django 5.2 on 2025-05-28 05:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_initial'),
        ('order', '0006_alter_order_order_id_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='od_eb6ccd41', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('6720ce9e-df0b-4ae9-954e-0a03a11df9b2')),
        ),
        migrations.CreateModel(
            name='ShippingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('receipent_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=30)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.userprofile')),
            ],
        ),
    ]
