# Generated by Django 5.2 on 2025-05-28 05:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_order_id_alter_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippinglocation',
            old_name='user',
            new_name='order_user',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='od_803a3c1f', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('f5acdd22-05ce-4fe5-8535-162bb141bd21')),
        ),
    ]
