# Generated by Django 5.2 on 2025-05-28 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_user_shippinglocation_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='od_97f11d27', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('d0163419-be56-4a77-a2ac-e58b3c76ca7f')),
        ),
    ]
