# Generated by Django 5.2 on 2025-06-04 04:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_order_id_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinglocation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='od_952bc812', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('2104f5ea-59f0-4daa-b1d1-39f8cf615e61')),
        ),
    ]
