# Generated by Django 5.2 on 2025-06-04 04:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_shippinglocation_is_active_alter_order_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippinglocation',
            old_name='order_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='od_b575e74f', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('28af5da4-3cc7-4630-9371-da167f5978b4')),
        ),
    ]
